version: '3'

services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdb
      - DB_USER=postgres
      - DB_PASS=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: