version: '3'

services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hierarchical-db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: